# Generated by Django 5.1.2 on 2025-01-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamp',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='preview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='shape',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
