# Generated by Django 5.1.2 on 2025-01-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0002_alter_stamp_color_alter_stamp_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp',
            name='canvas_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
