# Generated by Django 5.1.2 on 2025-01-29 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0003_stamp_canvas_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stamp',
            name='canvas_json',
        ),
    ]
