# Generated by Django 5.1.2 on 2025-02-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('qr_code_data', models.TextField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('Verified', 'Verified'), ('Error', 'Error'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('verification_message', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
