# Generated by Django 5.1.2 on 2025-02-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifydocs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='verification_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
