# Generated by Django 5.1.2 on 2025-02-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifydocs', '0002_alter_document_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='stamp_owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
