# Generated by Django 5.1.2 on 2025-01-26 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='stamp',
        ),
    ]
