# Generated by Django 5.1.2 on 2025-01-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_document_stamped'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='stamp_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='stamped',
            field=models.BooleanField(default=False),
        ),
    ]
