# Generated by Django 5.1.2 on 2025-01-29 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_stamp_data_document_stamped'),
        ('stamps', '0004_remove_stamp_canvas_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='stamp_data',
        ),
        migrations.AddField(
            model_name='document',
            name='stamp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='stamps.stamp'),
        ),
    ]
